In [ ]:
class Employee:
    # Class variable to count the number of employees
    employee_count = 0
    total_salary = 0

    def __init__(self, name, family, salary, department):
        # Instance variables
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        # Increment the employee count and add the salary to total salary
        Employee.employee_count += 1
        Employee.total_salary += salary

    @classmethod
    def average_salary(cls):
        if cls.employee_count == 0:
            return 0
        return cls.total_salary / cls.employee_count

    def __str__(self):
        return f"Employee Name: {self.name}, Family: {self.family}, Salary: {self.salary}, Department: {self.department}"

# FulltimeEmployee class inheriting from Employee class
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

# Creating instances of Employee class
employee1 = Employee("Jagannath Ganti", "Ganti", 500000, "IT")
employee2 = Employee("Arun Sai", "Sai", 600000, "Health")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Santosh Mallela", "Mallela", 700000, "Engineering")
fulltime_employee2 = FulltimeEmployee("Surya Vamsi", "Vamsi", 800000, "Marketing")

# Printing the employee details
print(employee1)
print(employee2)
print(fulltime_employee1)
print(fulltime_employee2)

# Printing the total number of employees and the average salary
print(f"Total Employees: {Employee.employee_count}")
print(f"Average Salary: {Employee.average_salary()}")


Employee Name: Jagannath Ganti, Family: Ganti, Salary: 500000, Department: IT
Employee Name: Arun Sai, Family: Sai, Salary: 600000, Department: Health
Employee Name: Santosh Mallela, Family: Mallela, Salary: 700000, Department: Engineering
Employee Name: Surya Vamsi, Family: Vamsi, Salary: 800000, Department: Marketing
Total Employees: 4
Average Salary: 650000.0


Created a class and two class variables " Employee" , " employee_count" and "total_salary" respectively.

Used "init" method to initiate " name", "family", "salary", "department".

"average_salary" is used to calculate the average of the employee salaries.

The "FulltimeEmployee" is inherited from "Employee" class.

Employee and FulltimeEmployee instances are created.

Employee details are printed

Average salary of the total number of employees are printed.

In [ ]:
import numpy as np

# Create a random vector of size 20 with floats in the range 10-20
random_vector = np.random.uniform(10, 20, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Get the indices of the maximum values in each row
max_indices = np.argmax(reshaped_array, axis=1)

# Create a copy of the reshaped array to not modify the original array
modified_array = reshaped_array.copy()

# Replace the max values with 0 without using for loop
modified_array[np.arange(reshaped_array.shape[0]), max_indices] = 0

# Output the results
print("Original reshaped array:\n", reshaped_array)
print("\nModified array with max in each row replaced by 0:\n", modified_array)


Original reshaped array:
 [[16.31988127 17.40286352 11.68819102 10.60518971 12.69248647]
 [16.43779071 18.72524093 11.01347313 10.20938746 18.64517639]
 [19.27794408 14.99713529 16.65628418 16.19611845 15.04978499]
 [13.65072676 14.59529707 15.53371821 11.03465591 15.61656396]]

Modified array with max in each row replaced by 0:
 [[16.31988127  0.         11.68819102 10.60518971 12.69248647]
 [16.43779071  0.         11.01347313 10.20938746 18.64517639]
 [ 0.         14.99713529 16.65628418 16.19611845 15.04978499]
 [13.65072676 14.59529707 15.53371821 11.03465591  0.        ]]


Used np.random.unfiorm(10,20,20) to create a random vector with floats in range 10-20.

Used random_vector.reshape(4,5) to reshape the array to 4 * 5.

np.argmax(reshaped_array, axis=1) was used to find the index of the maximum value  in each row.

reshaped_array.copy() was used to create a copy of the modified array.

modified_array[np.arange(reshaped_array.shape[0]), max_indices] = 0 was used to create an array [0,1,2,3] to represent the row indices.

modified_array[np.arange(reshaped_array.shape[0]), max_indices] = 0 was used to replace maximum values in each row with 0.


